export default {
  touched: {},
  errors: {},
  isSubmitting: false,
  isValidating: false,
  submitCount: 0,
  setStatus: () => undefined,
  setError: () => undefined,
  setErrors: () => undefined,
  setSubmitting: () => undefined,
  setTouched: () => undefined,
  setValues: () => undefined,
  setFieldValue: () => undefined,
  setFieldError: () => undefined,
  setFieldTouched: () => undefined,
  validateForm: async () => ({}),
  resetForm: () => undefined,
  submitForm: () => undefined,
  setFormikState: () => undefined,
  handleSubmit: () => undefined,
  handleChange: () => undefined,
  handleBlur: () => undefined,
  handleReset: () => undefined,
  registerField: () => undefined,
  unregisterField: () => undefined,
  validateField: () => undefined,
  dirty: false,
  isValid: false
};
